### ISSUE TITLE
Language selection menu is not displayed completely.

### ISSUE THREAD

**Issue by enrico3** [hsnborn22/LinGo#1]
Hello,
when I run the Windows exe the first menu starts with croatian and I also cannot scroll upwards.

![image](https://github.com/hsnborn22/LinGo/assets/31779179/baf648a8-f3c6-4369-9aff-8a617958ded0)

**Comment by hsnborn22** [comment]
I added a completely new UI for the first two menus; it should now be displayed correctly on all operating systems regardless of terminal size.
